"""Docker Compose target: the container subset of a design.

Only container-oriented blocks map to Compose — ECS services, databases (RDS -> a DB
container) and object storage (S3 -> MinIO). Infrastructure blocks (VPC, subnets, ALB,
IAM, …) are provisioned elsewhere and are reported as unmapped.
"""

import yaml

from app.ir.compiler import validate
from app.services.projectfmt import normalize_files

_DB = {
    "postgres": {"image": "postgres:16", "port": 5432, "datadir": "/var/lib/postgresql/data"},
    "mysql": {"image": "mysql:8", "port": 3306, "datadir": "/var/lib/mysql"},
    "mariadb": {"image": "mariadb:11", "port": 3306, "datadir": "/var/lib/mysql"},
}


def _db_env(engine: str, user: str, db: str) -> dict:
    if engine == "postgres":
        return {"POSTGRES_USER": user, "POSTGRES_PASSWORD": "${DB_PASSWORD:-change_me}", "POSTGRES_DB": db}
    return {
        "MYSQL_USER": user, "MYSQL_PASSWORD": "${DB_PASSWORD:-change_me}",
        "MYSQL_DATABASE": db, "MYSQL_ROOT_PASSWORD": "${DB_ROOT_PASSWORD:-change_me}",
    }


def compile_compose(ir: dict) -> dict:
    """Compile the container subset of an IR design into a Docker Compose project."""
    validate(ir)
    services: dict = {}
    volumes: dict = {}
    unmapped: list = []
    for node in ir["nodes"]:
        t, nid, p = node["type"], node["id"], node["props"]
        if t == "ecs_service":
            port = int(p.get("container_port", 80))
            svc = {
                "image": p.get("image", "public.ecr.aws/nginx/nginx:latest"),
                "ports": [f"{port}:{port}"],
                "restart": "unless-stopped",
            }
            replicas = int(p.get("desired_count", 2))
            if replicas != 1:
                svc["deploy"] = {"replicas": replicas}
            services[nid] = svc
        elif t == "rds":
            engine = p.get("engine", "postgres")
            spec = _DB.get(engine, _DB["postgres"])
            vol = f"{nid}-data"
            services[nid] = {
                "image": spec["image"],
                "environment": _db_env(engine, p.get("username", "appadmin"), nid),
                "ports": [f"{spec['port']}:{spec['port']}"],
                "volumes": [f"{vol}:{spec['datadir']}"],
                "restart": "unless-stopped",
            }
            volumes[vol] = {}
        elif t == "s3_bucket":
            vol = f"{nid}-data"
            services[nid] = {
                "image": "minio/minio",
                "command": 'server /data --console-address ":9001"',
                "ports": ["9000:9000", "9001:9001"],
                "environment": {"MINIO_ROOT_USER": "minioadmin", "MINIO_ROOT_PASSWORD": "${MINIO_PASSWORD:-minioadmin}"},
                "volumes": [f"{vol}:/data"],
                "restart": "unless-stopped",
            }
            volumes[vol] = {}
        else:
            unmapped.append(t)

    compose: dict = {}
    if services:
        compose["services"] = services
    if volumes:
        compose["volumes"] = volumes
    header = (
        f"# {ir['name']} - generated by Neviri-Ansi (Docker Compose)\n"
        "# Container workloads only; provision networking/IAM with the Terraform or Ansible target.\n"
    )
    body = (
        yaml.dump(compose, sort_keys=False, default_flow_style=False)
        if compose
        else "# No container workloads here — add an ECS service, database, or bucket.\n"
    )
    return normalize_files({
        "compose.yaml": header + body,
        ".env": "DB_PASSWORD=change_me\nDB_ROOT_PASSWORD=change_me\nMINIO_PASSWORD=minioadmin\n",
        "README.md": _readme(ir, unmapped),
    })


def _readme(ir: dict, unmapped: list) -> str:
    lines = [
        f"# {ir['name']} - Docker Compose",
        "",
        "Container workloads from your design. Run:",
        "",
        "```bash",
        "docker compose up -d",
        "```",
    ]
    if unmapped:
        lines += ["", "## Provisioned elsewhere", "",
                  "These design components are infrastructure, not containers — use the Terraform/CloudFormation target for them:", ""]
        lines += [f"- `{u}`" for u in sorted(set(unmapped))]
    return "\n".join(lines) + "\n"
