"""Kubernetes target: the container subset of a design.

ECS services and databases map to a Deployment + Service each. Infrastructure blocks
(VPC, subnets, ALB, IAM, …) are not Kubernetes objects and are reported as unmapped —
provision them with the Terraform/CloudFormation target and point the app at them.
"""

import yaml

from app.ir.compiler import validate
from app.services.projectfmt import normalize_files


def _deployment(name: str, image: str, port: int, replicas: int, env: list | None = None) -> dict:
    container: dict = {"name": name, "image": image, "ports": [{"containerPort": port}]}
    if env:
        container["env"] = env
    return {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {"name": name, "labels": {"app": name}},
        "spec": {
            "replicas": replicas,
            "selector": {"matchLabels": {"app": name}},
            "template": {"metadata": {"labels": {"app": name}}, "spec": {"containers": [container]}},
        },
    }


def _service(name: str, port: int) -> dict:
    return {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {"name": name},
        "spec": {"type": "ClusterIP", "selector": {"app": name}, "ports": [{"port": port, "targetPort": port}]},
    }


def compile_kubernetes(ir: dict) -> dict:
    """Compile the container subset of an IR design into Kubernetes manifests."""
    validate(ir)
    docs: list = []
    unmapped: list = []
    for node in ir["nodes"]:
        t, nid, p = node["type"], node["id"], node["props"]
        if t == "ecs_service":
            port = int(p.get("container_port", 80))
            image = p.get("image", "public.ecr.aws/nginx/nginx:latest")
            docs += [_deployment(nid, image, port, int(p.get("desired_count", 2))), _service(nid, port)]
        elif t == "rds":
            engine = p.get("engine", "postgres")
            user = p.get("username", "appadmin")
            if engine == "postgres":
                image, port = "postgres:16", 5432
                env = [{"name": "POSTGRES_USER", "value": user}, {"name": "POSTGRES_PASSWORD", "value": "change_me"},
                       {"name": "POSTGRES_DB", "value": nid}]
            else:
                image, port = "mysql:8", 3306
                env = [{"name": "MYSQL_USER", "value": user}, {"name": "MYSQL_PASSWORD", "value": "change_me"},
                       {"name": "MYSQL_DATABASE", "value": nid}, {"name": "MYSQL_ROOT_PASSWORD", "value": "change_me"}]
            docs += [_deployment(nid, image, port, 1, env), _service(nid, port)]
        else:
            unmapped.append(t)

    header = f"# {ir['name']} - generated by Neviri-Ansi (Kubernetes)\n"
    if docs:
        body = "\n---\n".join(yaml.dump(d, sort_keys=False, default_flow_style=False).rstrip() + "\n" for d in docs)
    else:
        body = "# No container workloads here — add an ECS service or database.\n"
    return normalize_files({"manifests.yaml": header + body, "README.md": _readme(ir, unmapped)})


def _readme(ir: dict, unmapped: list) -> str:
    lines = [
        f"# {ir['name']} - Kubernetes",
        "",
        "Container workloads from your design. Apply:",
        "",
        "```bash",
        "kubectl apply -f manifests.yaml",
        "```",
    ]
    if unmapped:
        lines += ["", "## Provisioned elsewhere", "",
                  "These design components are infrastructure, not Kubernetes objects — use Terraform/CloudFormation:", ""]
        lines += [f"- `{u}`" for u in sorted(set(unmapped))]
    return "\n".join(lines) + "\n"
