"""Terraform / OpenTofu target: render the canonical AWS resources as HCL."""

from app.ir import aws_resources  # noqa: F401  -- importing registers the AWS mappings
from app.ir.canonical import Block, LocalRef, Raw, Ref, to_resources
from app.services.projectfmt import normalize_files


def _scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _value(value, primary, indent: int) -> str:
    pad = " " * indent
    if isinstance(value, Ref):
        rtype, rname = primary[value.node]
        return f"{rtype}.{rname}.{value.attr}"
    if isinstance(value, LocalRef):
        return f"{value.type}.{value.name}.{value.attr}"
    if isinstance(value, Raw):
        return value.expr
    if isinstance(value, dict):
        inner = "".join(f"{pad}  {k} = {_value(v, primary, indent + 2)}\n" for k, v in value.items())
        return "{\n" + inner + pad + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_value(v, primary, indent) for v in value) + "]"
    return _scalar(value)


def _emit_block(block: Block, primary, indent: int) -> str:
    pad = " " * indent
    lines = [f"{pad}{block.name} {{"]
    for key, val in block.attrs.items():
        lines.append(f"{pad}  {key} = {_value(val, primary, indent + 2)}")
    lines.append(f"{pad}}}")
    return "\n".join(lines)


def _emit_resource(resource, primary) -> str:
    lines = [f'resource "{resource.type}" "{resource.name}" {{']
    for key, val in resource.attrs.items():
        if isinstance(val, list) and not val:
            continue  # omit empty block-lists (e.g. a security group with no ingress rules)
        if isinstance(val, Block):
            lines.append(_emit_block(val, primary, 2))
        elif isinstance(val, list) and all(isinstance(x, Block) for x in val):
            lines.extend(_emit_block(b, primary, 2) for b in val)
        else:
            lines.append(f"  {key} = {_value(val, primary, 2)}")
    lines.append("}")
    return "\n".join(lines)


_PROVIDER = '''terraform {
  required_version = ">= 1.3"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}
'''


def _variables(region: str) -> str:
    return f'''variable "region" {{
  description = "AWS region to deploy into"
  type        = string
  default     = "{region}"
}}

variable "default_ami" {{
  description = "AMI id for EC2 instances / launch templates"
  type        = string
  default     = "ami-0c55b159cbfafe1f0"
}}

variable "lambda_role_arn" {{
  description = "Execution role ARN for Lambda functions (if any are used)"
  type        = string
  default     = ""
}}

variable "db_password" {{
  description = "Master password for RDS (override with TF_VAR_db_password)"
  type        = string
  default     = "CHANGE_ME_IN_A_SECRET"
  sensitive   = true
}}
'''


def _readme(ir: dict, unmapped: list) -> str:
    lines = [
        f"# {ir['name']} — Terraform",
        "",
        f"Provider: AWS · Region: {ir['region']}",
        "",
        "## Run",
        "```bash",
        "terraform init      # or: tofu init",
        "terraform plan",
        "terraform apply",
        "```",
    ]
    if unmapped:
        lines += ["", "## Not yet mapped", "", "These designed components have no Terraform mapping yet and were skipped:", ""]
        lines += [f"- `{u}`" for u in sorted(set(unmapped))]
    return "\n".join(lines) + "\n"


def compile_terraform(ir: dict) -> dict:
    """Compile an IR design into a Terraform project ({path: content})."""
    resources, primary, unmapped = to_resources(ir)
    body = "\n\n".join(_emit_resource(r, primary) for r in resources)
    notice = ""
    if unmapped:
        notice = f"# NOTE: not yet mapped to Terraform, skipped: {', '.join(sorted(set(unmapped)))}\n\n"
    main = f"# {ir['name']} — generated by Neviri-Ansi (Terraform)\n\n{notice}{body}\n"
    return normalize_files({
        "main.tf": main,
        "provider.tf": _PROVIDER,
        "variables.tf": _variables(ir["region"]),
        ".gitignore": ".terraform/\n*.tfstate\n*.tfstate.*\n.terraform.lock.hcl\n*.tfvars\n",
        "README.md": _readme(ir, unmapped),
    })
